---
title: 'Project 1: Exploratory Data Analysis'
author: "SDS348 Fall 2019"
date: "9/16/2019"
output:
  html_document:
    toc: yes
    toc_float:
      collapsed: no
      smooth_scroll: yes
  pdf_document:
    default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## Data Wrangling and Data Exploration

### Instructions
A knitted R Markdown document (as a PDF) and the raw R Markdown file (as .Rmd) should both be submitted to Canvas by 11:59pm on 10/13/2019. These two documents will be graded jointly, so they must be consistent (i.e., don’t change the R Markdown file without also updating the knitted document). Knit an html copy too, for later!

I envision your written text forming something of a narrative structure around your code/output. All results presented must have corresponding code. Any answers/results/plots etc. given without the corresponding R code that generated the result will not be graded. Furthermore, all code contained in your final project document should work properly. Please do not include any extraneous code or code which produces error messages. (Code which produces warnings is acceptable, as long as you understand what the warnings mean).

### Find data:

Find two (!) datasets with one variable in common (e.g., dates, years, states, counties, countries), both with at least 50 observations (i.e., rows) in each. When combined, the resulting/final dataset must have **at least 4 different variables (at least 2 numeric) in addition to the common variable**.

Choose as many as you would like! If you found two datasets that you like but they don't have enough variables,  find a third dataset with the same common variable and join all three. 


### Guidelines

1. If the datasets are not tidy, you will need to reshape them so that every observation has its own row and every variable its own column. If the datasets are both already tidy, you will make them untidy with spread() and then tidy them again with gather() to demonstrate your use of the functions.

    - It would be a good idea to do this before joining. For example, if you have a dataset you like with multiple measurements per year, but you want to join by year, you could average over your numeric variables to get means/year, do counts for your categoricals to get a counts/year, etc.
    

2. Join your 2+ separate data sources into a single dataset

    - You will document the type of join that you do (left/right/inner/full), including how many cases in each dataset were dropped and why you chose this particular join


3. Create summary statistics

    - Use *all six* core `dplyr` functions (filter, select, arrange, group_by, mutate, summarize) to manipulate and explore your dataset. For mutate, create a  new variable that is a function of at least one other variable, preferably using a dplyr vector function (see dplyr cheatsheet). 
    
    - Create summary statistics (mean, sd, var, n, quantile, min, max, n_distinct, cor, etc) for each of your numeric variables after grouping by your categorical variables (either together or one-at-a-time; if you have two categorical variables, include at least one statistic based on a grouping of two categorical variables simultaneously). If you do not have any categorical variables, create one using mutate to satisfy the requirements above.
 
4. Make visualizations

    - If you have 5 variables (the minimum), with 2 numeric variables (the minimum), create at least two effective plots with ggplot that illustrate some of the more interesting findings that your descriptive statistics have turned up.
    - Each plot should have at least three variables mapped to separate aesthetics
    - At least one plot should include `stat="summary"`
    - Each plot should include a supporting paragraph describing the relationships that are being visualized and any notable trends that are apparent
        - It is fine to include more, but limit yourself to 4. Plots should not be redundant! Four bad plots will get a lower grade than two good plots!
    
5. Perform k-means clustering or PCA on your numeric variables.

    - Include all steps as we discuss in class, including a visualization.

    - If you don't have at least 3 numeric variables, create dummy variables ("one-hot" encoding) using one of your categorical variables.
    
    - If you want to get fancy, or can't reasonably recode one of your categoricals, throw all your variables in and do PAM on Gower's distance matrix
    
- For every step, you should document what your code does (in words) and what you see in the data. For each plot, include a description of     
    
    
### Rubric

Prerequisite: Finding appropriate data from at least two sources per the instructions above: Failure to do this will result in a 0! You will submit a .Rmd file and a knitted document (pdf).

#### 0. Introduction (4  pts)

- Write a narrative introductory paragraph (or two) describing the datasets you have chosen, the variables they contain, how they were acquired, and why they are interesting to you. Expand on potential associations you may expect, if any.

#### 1. Tidying: Spread/Gather (8 pts)

- Tidy the datasets (using the `tidyr` functions `gather` and/or `spread`) 
- If you data sets are already tidy, untidy them, retidy them.
- Document the process (describe in words what was done)
    
#### 2. Joining/Merging (8 pts)

- Join your datasets into one using a `dplyr` join function
- If you have multiple observations on the joining variable in either dataset, fix this by collapsing via summarize
- Discuss the process in words, including why you chose the join you did
- Discuss which cases were dropped, if any, and potential problems with this

#### 3. Wrangling (40 pts)

- Use all six core `dplyr` functions in the service of generating summary statistics (18 pts)
    - Use mutate to generate a variable that is a function of at least one other variable

- Compute at least 10 different summary statistics using summarize and summarize with group_by (18 pts)
    - At least 5 of these should group by a categorical variable. Create one by dichotomizing a numeric if necessary
    - If applicable, at least 1 of these 5 should group by two categorical variables

- Summarize/discuss all results in no more than two paragraphs (4 pts)


#### 4. Visualizing (30 pts)

- Create two effective, polished plots with ggplot

    - Each plot should map 3 of your variables to aesthetics
    - Each plot should have a title and clean labeling for all mappings
    - Change at least one default theme element and color for at least one mapping per plot
    - For at least one plot, add more tick marks (x, y, or both) than are given by default
    - For at least one plot, use the stat="summary" function
    - Supporting paragraph or two (for each plot) describing the relationships/trends that are apparent
    
#### 5. Dimensionality Reduction (20 pts) 

- Either k-means clustering or PCA (inclusive "or") should be performed on at least three numeric variables in your dataset

    - All relevant steps discussed in class should be included/reported
    - A visualization of the clusters or the first few principal components (using ggplot2)
    - Supporting paragraph or two describing results found 
    

### Where do I find data?

OK, brace yourself!

You can choose ANY datasets you want that meet the above criteria for variables and observations. I'm just sitting here but off the top of my head, if you are into amusement parks, you could look at amusement-park variables, including visits, and how they are impacted by weather. If you are interested in Game of Thrones, you could look at how the frequency of mentions of character names (plus other character variables) and the frequency of baby names in the US...You could even take your old Biostats data and merge in new data (e.g., based on a Google forms timestamp).

You can make it as serious as you want, or not, but keep in mind that you will be incorporating this project into a portfolio webpage for your final in this course, so choose something that really reflects who you are, or something that you feel will advance you in the direction you hope to move career-wise, or something that you think is really neat. On the flip side, regardless of what you pick, you will be performing all the same tasks, so it doesn't end up being that big of a deal.

If you are totally clueless and have no direction at all, log into the server and type 

```{R eval=F}
data(package = .packages(all.available = TRUE))
```

This will print out a list of **ALL datasets in ALL packages** installed on the server (a ton)! Scroll until your eyes bleed! Actually, do not scroll that much... To start with something more manageable, just run the command on your own computer, or just run `data()` to bring up the datasets in your current environment. To read more about a dataset, do `?packagename::datasetname`. 

If it is easier for you, and in case you don't have many packages installed, a list of R datasets from a few common packages (also downloadable in CSV format) is given at the following website: https://vincentarelbundock.github.io/Rdatasets/datasets.html

- A good package to download for fun/relevant data is `fivethiryeight`. Just run `install.packages("fivethirtyeight"), load the packages with `library(fivethirtyeight)`, run `data()`, and then scroll down to view the datasets. Here is an online list of all 127 datasets (with links to the 538 articles). Lots of sports, politics, current events, etc.

- If you have already started to specialize (e.g., ecology, epidemiology) you might look at discipline-specific R packages (vegan, epi, respectively). We will be using some tools from these packages later in the course, but they come with lots of data too, which you can explore according to the directions above

- However, you *emphatically DO NOT* have to use datasets available via R packages! In fact, I would much prefer it if you found the data from completely separate sources and brought them together (a much more realistic experience in the real world)! You can even reuse data from your SDS328M project, provided it shares a variable in common with other data which allows you to  merge the two together (e.g., if you still had the timestamp, you could look up the weather that day: https://www.wunderground.com/history/). If you work in a research lab or have access to old data, you could potentially merge it with new data from your lab!

- Here is a curated list of interesting datasets (read-only spreadsheet format): https://docs.google.com/spreadsheets/d/1wZhPLMCHKJvwOkP4juclhjFgqIY8fQFMemwKL2c64vk/edit

- Here is another great compilation of datasets: https://github.com/rfordatascience/tidytuesday

- Here is the UCI Machine Learning Repository: https://archive.ics.uci.edu/ml/index.php

    - See also https://en.wikipedia.org/wiki/List_of_datasets_for_machine-learning_research#Biological_data

- Here is another good general place to look: https://www.kaggle.com/datasets

- To help narrow your search down or to see interesting variable ideas, check out https://www.tylervigen.com/spurious-correlations. This is the spurious correlations website, and it is fun, but if you look at the bottom of each plot you will see sources for the data. This is a good place to find very general data (or at least get a sense of where you can scrape data together from)!

- If you are interested in medical data, check out www.countyhealthrankings.org

- If you are interested in scraping UT data, they make *loads* of data public (e.g., beyond just professor CVs and syllabi). Check out all the data that is available in the statistical handbooks: https://reports.utexas.edu/statistical-handbook

##### Broader data sources:

[Data.gov](www.data.gov) 186,000+ datasets!

[Social Explorer](Social Explorer) is a nice interface to Census and American Community Survey data (more user-friendly than the government sites). May need to sign up for a free trial.

[U.S. Bureau of Labor Statistics](www.bls.gov)

[U.S. Census Bureau](www.census.gov)

[Gapminder](www.gapminder.org/data), data about the world.
```{R}

library(tidyverse)
library(ggplot2)
usage0 <- read.csv("./usage2.csv")
usage1500 <- read.csv("./usage1500.csv")
usage1695 <- read.csv("./usage1695.csv")
usage1875 <- read.csv("./usage1875.csv")
pokemon <- read.csv("./pokemon.csv")


```

###Introduction

These are the datasets I will be using for this project. It took me a while to decide what datasets to chose that were meaningful to me. Originally, I planned on working with something related to biology, but the datasets that I looked at did not have many variables in common. Even if they were measuring the same thing, such as leaf length, different datasets measure different species or molecules that have different properties. So, I decided to look at Pokémon, since I knew there was a dataset available from class and I am familiar with other datasets as well.

The dataset I chose comes from smogon.com, which is a site for competitive Pokémon battling where people can simulate battles against each other, discuss strategies, etc. They have their own battle simulator, known as "Pokémon Showdown!" which is where they get data from hundreds of thousands of games played. Because of the sheer number of Pokémon, players can chose to battle in different "tiers" where only certain Pokémon are allowed. The tiers are based on the usage of each Pokémon, that is,  how often they are chosen in battle. To keep things simpler, I am only looking at the most popular tier, called "Overused" or "OU", where a majority of Pokémon are allowed, bar a few powerful legendaries. The data here are divided by elo, so I had to obtain four different sets of data from Smogon. Also, because newer Pokémon have been released, they are missing from the dataset we saw in class, which will not be considered in this project. The usage variable is the percentage of games one is found, whereas raw is the total number of games. The data is complied from one month's worth of games. The elo variable is the rank of the players the statistics come from. 

###Tidying

Although there are several variables for each condition, the datset is already tidy. the "real" statistic shows only the times when a Pokémon is sent out in battle, but doesn't actually have to fight. It is a separate statistic, albeit a subset of the unweighed usage (it can be higher than unweighted for stronger Pokémon). However, I will not be using that statistic as it is an unecessary restriction. 

```{R}

uwider <- usage0 %>% separate(usage_weighed, into = c("usage", "weighed")) %>% pivot_wider(names_from = "Name", values_from = "usage")

ulonger <- uwider %>% pivot_longer(8:905, names_to = "Pokemon", values_to = "usage") %>% na.omit() %>% unite("usage_weighed", usage, weighed, sep=".")

head(ulonger)

usage0 <- usage0 %>% select(-raw_real, -usage_real, -X)
usage1500 <- usage1500 %>% select(-raw_real, -usage_real, -X)
usage1695 <- usage1695 %>% select(-raw_real, -usage_real, -X)
usage1875 <- usage1875 %>% select(-raw_real, -usage_real, -X)


```

Here I untidied the dataset using pivot wider and separate to demonstrate how to tidy it back up. na omit here is necessary due to the large number of NAs generated by the pivot wider function, which contained several NAs for each Pokémon. Unite brings the separated columns back together, which requires a sep specifier, which I chose to be "." since the numbers were originally decimals. I also changed the percentages to numeric variables, since there was no way to work with them as characters. This took a considerable amount of time to work out, but eventually I managed to do it. However, I decided to do it after joining the datasets.  

###Joining Datasets

```{R}
pokestat <- full_join(usage0, usage1500, by=c("Name","usage_weighed", "raw_unweighed", "elo", "usage_unweighed")) %>% full_join(usage1695, by=c("Name","usage_weighed", "raw_unweighed", "elo", "usage_unweighed")) %>% full_join(usage1875, by=c("Name","usage_weighed", "raw_unweighed", "elo", "usage_unweighed")) %>% full_join(pokemon)

pokestat <- pokestat[!is.na(pokestat$Total), ]
pokestat <- pokestat[!is.na(pokestat$usage_weighed), ]

a1 <- pokestat %>% separate(usage_weighed, into=c("usage","weighed"))
a1 <- a1%>%unite("usage_weighed", usage, weighed, sep=".")
a1$usage_weighed <- as.numeric(as.character(a1$usage_weighed))

a1 <- a1 %>% separate(usage_unweighed, into=c("usage","unweighed"))
a1 <- a1%>%unite("usage_unweighed", usage, unweighed, sep=".")
a1$usage_unweighed <- as.numeric(as.character(a1$usage_unweighed))
pokestat <- a1

```

###Wrangling

```{R}
pokestat %>% select(Name, Speed) %>% mutate(minSpeed = floor((2*Speed + 5)*0.9)) %>% mutate(maxSpeed = floor((2*Speed + 5 + (252/4) + 31) * 1.1 )) %>% head()
```
The formulas here aren't really important, but it is nice to see that they work. they represent the stats at lv100 from min to max.

```{R}
pokestat <- pokestat %>% rename("Type1" = 'Type.1', "Type2" = 'Type.2', "dexNo"='X.')

pokestat %>% group_by(Type1, Type2) %>% filter(str_detect(Name, "Mega")) %>% summarize(mean=mean(Total), usage=mean(raw_unweighed)) %>% arrange(desc(mean)) %>% head()
#Mega only

pokestat %>% group_by(Type1, Type2) %>% summarize(mean=mean(Total), usage=mean(raw_unweighed), usagesd = sd(raw_unweighed)) %>% arrange(desc(mean))
#Overall

pokestat %>% group_by(Type1, Type2) %>% filter(Legendary == T) %>% summarize(mean=mean(Total), usage=mean(raw_unweighed)) %>% arrange(desc(mean)) %>% head()
#Legendary Only

pokestat %>% group_by(Generation) %>% summarize(meanTotal=mean(Total), usage=mean(raw_unweighed))
#total and usage by generation

pokestat %>% group_by(Generation) %>% summarize(meanSpeed=mean(Speed), meanAttack=mean(Attack), meanHP=mean(HP), usage=mean(raw_unweighed), usagesd = sd(raw_unweighed))
#some stats by generation and usage

pokestat %>% select(dexNo, Name, usage_weighed) %>% arrange(desc(usage_weighed)) %>% head()
#Pokedex number by usage

pokestat %>% select(-Generation, -Type1, -Type2, -Legendary, -Name, -dexNo, -elo) %>% cor()
#Correlation matrix

```

###Visualizing

```{R}
pokestat %>% group_by(Generation) %>% ggplot(aes(x=Generation, y=raw_unweighed, fill=(Type1)))+geom_bar(stat="summary") +ggtitle("Usage Distribution by Generation")+labs(x="Generation", y="Unweighted Usage") + theme_dark()+theme(legend.position = "bottom") + scale_x_continuous("Generation", 1:6)


```
This graph showing the mean unweighted usage for each generation of Pokémon. Interestingly, one would expect that newer Pokémon would be stronger than older Pokémon, but this is not actually the case here. I also added a fill color representing the Type1. It can be used to show the proportion of pokemon of each Type introduced in each generation.


```{R}
pokestat %>% ggplot(aes(x=Type1, y=Type2, color=(Total)))+geom_point()+ggtitle("Base Stat Total Distributed by Type")+labs(x="Type 1", y="Type 2")+ theme(axis.text.x = element_text(angle = 90, hjust = 1))
```
This graph shows a Base Stat Total Distirbution by Type. It is interesting to note a few things here: the darker dots are lower in stat total, which can be seen on the left edge and the top edge. This shows that bug type Pokémon in particular tend to have the lowest stats. Additionally, Pokémon with only one type have lower stats as well (NA at the top). This makes sense because the unevolved Pokémon usually only have one type and are weaker in general as well. Some of the stronger types include Dragon, Psychic and Fire.

```{R}
pokestat %>% ggplot(aes(x=Type1, y=Type2, color=(usage_weighed)))+geom_point()+ggtitle("Weighted Usage Distributed by Type")+labs(x="Type 1", y="Type 2")+ theme(axis.text.x = element_text(angle = 90, hjust = 1))
```
This plot is similar to the previous one. It shows the same thing but for weighted usage rather than type. It is interesting to note that there is not much variation between each type combination. This is probably best explained by the fact that more diverse teams are better than ones centralized on a certain type, as they cover more weaknesses. Because of this, most types are represented fairly equally. 

###Principal Component Analysis 

```{R}
b1 <- pokestat %>% select(-Generation, -dexNo) %>% select_if(is.numeric) %>% scale()
rownames(b1) <- pokestat$Name
b2<-princomp(b1)
b2 %>% summary(loadings=T)
eigen <- b2$sdev^2
varprop=round(eigen/sum(eigen),2)

pokedf<-data.frame(PC1=b2$scores[,1], PC2=b2$scores[,2])
ggplot(pokedf,aes(PC1, PC2))+geom_point()

Name<-pokestat$Name
b2$scores%>%as.data.frame%>%cbind(Name,.)%>%top_n(3,Comp.1)
b2$scores%>%as.data.frame%>%cbind(Name,.)%>%top_n(3,wt=desc(Comp.1))
b2$scores%>%as.data.frame%>%cbind(Name,.)%>%top_n(3,wt=Comp.2) 
b2$scores%>%as.data.frame%>%cbind(Name,.)%>%top_n(3,wt=desc(Comp.2))
```

```{R}
b2$loadings[1:7,1:2]%>%as.data.frame%>%rownames_to_column%>%
ggplot()+geom_hline(aes(yintercept=0),lty=2)+
 geom_vline(aes(xintercept=0),lty=2)+ylab("PC2")+xlab("PC1")+
 geom_segment(aes(x=0,y=0,xend=Comp.1,yend=Comp.2),arrow=arrow(),col="red")+
 geom_label(aes(x=Comp.1*1.1,y=Comp.2*1.1,label=rowname))
```

Interestingly here, the base stats seem to be less correlated to usage as one may think. This suggests there may be other factors affecting the usage of certain Pokémon, and likewise that usage does not tell the strength of the Pokémon in all aspects. This is especially evident looking at the lowest in PC2, Regigigas, which has very high base stats but suffers competitively due to its detrimental ability (not considered in this project). 

```{R}
pokestat%>%select(-Generation, -dexNo) %>% select_if(is.numeric) %>% mutate_all(function(x)log(x+1))%>%
 prcomp()->poke_pca
summary(poke_pca)
```

```{R}
eigvals<-poke_pca$sdev^2
varprop<-round(eigvals/sum(eigvals),2)

results<-pokestat%>%as.data.frame%>%
 mutate(PC1=poke_pca$x[,1],PC2=poke_pca$x[,2])

results%>%ggplot(aes(PC1,PC2,color=Total, shape=Legendary))+geom_point(size=3)

results%>%ggplot(aes(PC1,PC2,color=usage_unweighed, shape=Legendary))+geom_point(size=3)

results%>%ggplot(aes(PC1,PC2,color=Type1, shape=Legendary))+geom_point(size=3)

```

So, the results here seem to suggest that PC2 is able to account for over 90 percent of the data. However, it is difficult to see which variable account for most of the variation. It seems that PC1 divides the most by Type1. Looking at the first graph, this makes sense, as despite including a variety of types, the right-hand side has more green points corresponding to Fighting, Fire, Flying and Ghost types whereas the left-hand side has more blue points corresponding to Normal, Ice, Ground and Poison types. Vertically, it can be seen clearly that both Legendary status but to a higher degree the usage divide the few points at the bottom from the rest. This is especially noticable in unweighed rather than weighed usage. This makes sense when looking at the highest for PC1 and PC2, both of which were LandorusTherian, a Pokémon that is ubiquitous in competitive play, although the reasons for such are more complex than just stats and typing. Total also divides the data verticalaly, which is to be expected as stronger Pokémon will be much more different than weaker Pokémon, even only accounting for stats. 
...